import Head from 'next/head';
import React from 'react';

const Layout = ({children}) => {
  return <div className="bg-bc text-primary ">
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Dongle&family=Kaushan+Script&display=swap" rel="stylesheet"></link>
        

      </Head>
      {children}
  </div>;
};

export default Layout;
